"""
database.py
===========
SQLite persistence layer for GuardianVision AI, built on SQLAlchemy.

Stores every detected violation as an `Incident` row, giving the API
and dashboard a durable source of truth beyond in-memory state.

Usage
-----
    from app.utils.database import init_db, save_incident, get_recent_incidents

    init_db()
    save_incident(worker_id=7, camera_id="cam_01", missing_ppe=["helmet"], ...)
    incidents = get_recent_incidents(limit=50)
"""

from __future__ import annotations

from contextlib import contextmanager
from datetime import datetime
from pathlib import Path
from typing import Generator, List, Optional

from sqlalchemy import Column, DateTime, Float, Integer, String, create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from app.utils.config_loader import get_config
from app.utils.logger import get_logger

logger = get_logger(__name__)


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""


class Incident(Base):
    """
    ORM model representing a single PPE compliance violation event.

    Each row corresponds to one alert generated by the violation engine:
    a specific tracked worker, on a specific camera/zone, missing one or
    more required PPE items at a point in time.
    """

    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, autoincrement=True)
    worker_id = Column(Integer, nullable=False, index=True)
    camera_id = Column(String(64), nullable=False, index=True)
    zone_id = Column(String(64), nullable=False, index=True)
    missing_ppe = Column(String(256), nullable=False)  # comma-separated
    risk_level = Column(String(16), nullable=False)
    confidence = Column(Float, nullable=False)
    screenshot_path = Column(String(512), nullable=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)

    def to_dict(self) -> dict:
        """Serialize the ORM row into a plain dict (for API / CSV / JSON export)."""
        return {
            "id": self.id,
            "worker_id": self.worker_id,
            "camera_id": self.camera_id,
            "zone_id": self.zone_id,
            "missing_ppe": self.missing_ppe.split(",") if self.missing_ppe else [],
            "risk_level": self.risk_level,
            "confidence": self.confidence,
            "screenshot_path": self.screenshot_path,
            "timestamp": self.timestamp.isoformat(),
        }


_engine = None
_SessionLocal: Optional[sessionmaker] = None


def init_db(database_path: Optional[str] = None) -> None:
    """
    Initialize the database engine and create tables if they don't exist.

    Safe to call multiple times; subsequent calls are no-ops if the engine
    is already initialized.
    """
    global _engine, _SessionLocal

    if _engine is not None:
        return

    config = get_config()
    db_path = database_path or config.reports.database_path

    # Ensure parent directory exists (e.g. `reports/`)
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)

    _engine = create_engine(f"sqlite:///{db_path}", echo=False, future=True)
    _SessionLocal = sessionmaker(bind=_engine, expire_on_commit=False)

    Base.metadata.create_all(_engine)
    logger.info(f"Database initialized at {db_path}")


@contextmanager
def get_session() -> Generator[Session, None, None]:
    """Context-managed database session with automatic commit/rollback."""
    if _SessionLocal is None:
        raise RuntimeError("Database not initialized. Call init_db() first.")

    session = _SessionLocal()
    try:
        yield session
        session.commit()
    except Exception:
        session.rollback()
        logger.exception("Database transaction failed; rolled back.")
        raise
    finally:
        session.close()


def save_incident(
    worker_id: int,
    camera_id: str,
    zone_id: str,
    missing_ppe: List[str],
    risk_level: str,
    confidence: float,
    screenshot_path: Optional[str] = None,
) -> Incident:
    """
    Persist a new violation incident to the database.

    Returns
    -------
    Incident
        The saved ORM row, with its generated primary key populated.
    """
    with get_session() as session:
        incident = Incident(
            worker_id=worker_id,
            camera_id=camera_id,
            zone_id=zone_id,
            missing_ppe=",".join(missing_ppe),
            risk_level=risk_level,
            confidence=confidence,
            screenshot_path=screenshot_path,
            timestamp=datetime.utcnow(),
        )
        session.add(incident)
        session.flush()
        session.refresh(incident)
        logger.info(
            f"Incident logged: worker={worker_id} camera={camera_id} "
            f"missing={missing_ppe} risk={risk_level}"
        )
        return incident


def get_recent_incidents(limit: int = 100, camera_id: Optional[str] = None) -> List[dict]:
    """
    Retrieve the most recent incidents, optionally filtered by camera.

    Returns a list of plain dicts (already detached from the ORM session).
    """
    with get_session() as session:
        query = session.query(Incident).order_by(Incident.timestamp.desc())
        if camera_id:
            query = query.filter(Incident.camera_id == camera_id)
        rows = query.limit(limit).all()
        return [row.to_dict() for row in rows]


def get_incident_stats() -> dict:
    """Return aggregate counts used by the dashboard summary cards."""
    with get_session() as session:
        total = session.query(Incident).count()
        high_risk = session.query(Incident).filter(Incident.risk_level == "high").count()
        return {
            "total_incidents": total,
            "high_risk_incidents": high_risk,
        }
